### ISSUE TITLE
Do you need help?

### ISSUE THREAD

**Issue by miquelvir** [mzaglia/flask-redoc#4]
Title is quite self-explanatory; do you need help with something?

**Comment by mzaglia** [comment]
Hi @miquelvir ! Thanks for reaching out! 

At the moment I'm satisfied with the current state of features.

You're more then welcome to contribute in anything that you think it would improve the lib.

**Comment by miquelvir** [comment]
Okey, if I find something I'll let you know! I have started using it today, and for my usecase it is way better than flasgger...

If you need anything just let me know! Also, do you plan on submitting this as an official Flask extension?

**Comment by mzaglia** [comment]
Could be something to do in the future after some polishing in the code and documentation.
